# Generated by Django 6.0.5 on 2026-05-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('diagram', 'Wiring Diagram'), ('audio', 'Audio Recording'), ('video', 'Video Recording'), ('document', 'Document')], max_length=50),
        ),
    ]
