# Generated by Django 6.0.5 on 2026-05-26 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_multimedia_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimedia',
            name='maintenance_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multimedia_files', to='maintenance.maintenancelog'),
        ),
    ]
